import Mathlib.GroupTheory.Perm.Sign
import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.GroupTheory.SpecificGroups.Alternating
import Mathlib.GroupTheory.SpecificGroups.Dihedral
import Mathlib.Tactic

namespace Solutions.GroupTheory.Permutations

open Equiv Equiv.Perm

private def q7Permutation : Perm (Fin 5) := swap 0 1 * (swap 2 3 * swap 3 4)

theorem q1_swap_product :
    swap (0 : Fin 4) 1 * swap 1 2 * swap 2 3 = finRotate 4 := by
  -- Composing the three adjacent transpositions `(0 1)(1 2)(2 3)` threads every point one step
  -- forward: the result is the 4-cycle `0 → 1 → 2 → 3 → 0`.
  ext i
  fin_cases i <;> rfl


theorem q2_sign_swap : Perm.sign (swap (0 : Fin 4) 1) = -1 := by
  -- A single transposition swaps two points and fixes the rest, so it is odd.
  exact sign_swap (by norm_num)


theorem q3_sign_cycle_length :
    Perm.sign (finRotate 4) = -1 ∧ Perm.sign (finRotate 5) = 1 := by
  -- Write each cycle as adjacent transpositions, then count the signs of those transpositions.
  have h4 : finRotate 4 = swap (0 : Fin 4) 1 * swap 1 2 * swap 2 3 := by
    ext i
    fin_cases i <;> rfl
  have h5 : finRotate 5 = swap (0 : Fin 5) 1 * swap 1 2 * swap 2 3 * swap 3 4 := by
    ext i
    fin_cases i <;> rfl
  rw [h4, h5]
  simp [Perm.sign_mul]


theorem q4_swaps_generate (σ : Perm (Fin 4)) :
    σ ∈ Subgroup.closure {τ : Perm (Fin 4) | τ.IsSwap} := by
  -- Build `σ` up one transposition at a time: the identity lies in every subgroup, and prepending
  -- a transposition keeps us inside the subgroup generated by the transpositions.
  refine swap_induction_on σ (Subgroup.one_mem _) ?_
  intro f x y hxy hf
  exact Subgroup.mul_mem _ (Subgroup.subset_closure ⟨x, y, hxy, rfl⟩) hf


theorem q5_three_cycle_even : Perm.sign (swap (0 : Fin 5) 1 * swap 1 2) = 1 := by
  -- A 3-cycle is a product of two transpositions, hence even.
  simp [Perm.sign_mul]


theorem q6_alternating_index_two : (alternatingGroup (Fin 4)).index = 2 := by
  -- The alternating group is the kernel of `sign`, so its index is the size of the image of
  -- `sign`. Since `sign` is onto `{±1}`, that image has `2` elements.
  rw [show alternatingGroup (Fin 4) = (Equiv.Perm.sign).ker from rfl, Subgroup.index_ker,
    MonoidHom.range_eq_top.mpr (sign_surjective _),
    Nat.card_congr Subgroup.topEquiv.toEquiv, Nat.card_eq_fintype_card]
  rfl


theorem q7_order_eq_lcm :
    orderOf (swap (0 : Fin 5) 1 * (swap 2 3 * swap 3 4)) = 6 := by
  -- The sixth power is the identity. The first five positive powers move a vertex.
  change orderOf q7Permutation = 6
  refine (orderOf_eq_iff (by norm_num)).mpr ⟨?_, ?_⟩
  · ext i
    fin_cases i <;> rfl
  · intro m hm hm0
    interval_cases m <;> try omega
    · intro h
      have he := DFunLike.congr_fun h (0 : Fin 5)
      have hmove : (q7Permutation ^ 1) 0 = 1 := by rfl
      rw [hmove] at he
      norm_num at he
    · intro h
      have he := DFunLike.congr_fun h (2 : Fin 5)
      have hmove : (q7Permutation ^ 2) 2 = 4 := by rfl
      rw [hmove] at he
      have hval := congrArg Fin.val he
      norm_num at hval
    · intro h
      have he := DFunLike.congr_fun h (0 : Fin 5)
      have hmove : (q7Permutation ^ 3) 0 = 1 := by rfl
      rw [hmove] at he
      norm_num at he
    · intro h
      have he := DFunLike.congr_fun h (2 : Fin 5)
      have hmove : (q7Permutation ^ 4) 2 = 3 := by rfl
      rw [hmove] at he
      have hval := congrArg Fin.val he
      norm_num at hval
    · intro h
      have he := DFunLike.congr_fun h (0 : Fin 5)
      have hmove : (q7Permutation ^ 5) 0 = 1 := by rfl
      rw [hmove] at he
      norm_num at he


theorem q8_cycle_decomp_concrete :
    (finRotate 4) ^ 2 = swap (0 : Fin 4) 2 * swap 1 3 := by
  -- Squaring the 4-cycle `0 → 1 → 2 → 3` sends `0 ↔ 2` and `1 ↔ 3`: it breaks into two disjoint
  -- transpositions.
  ext i
  fin_cases i <;> rfl


theorem q9_fifteen_puzzle_parity : Perm.sign (swap (3 : Fin 15) 4) = -1 := by
  -- Swapping two distinct tiles is a single transposition, hence odd.
  exact sign_swap (by omega)


theorem q10_square_dihedral_relations :
    (finRotate 4) ^ 4 = 1 ∧ (swap (1 : Fin 4) 3) ^ 2 = 1 ∧
      swap 1 3 * finRotate 4 * swap 1 3 = (finRotate 4)⁻¹ := by
  refine ⟨?_, ?_, ?_⟩
  · ext i
    fin_cases i <;> rfl
  · rw [pow_two, swap_mul_self]
  · ext i
    fin_cases i <;> rfl


theorem q11_noncommutative : ∃ σ τ : Equiv.Perm (Fin 3), σ * τ ≠ τ * σ :=
  -- Two overlapping transpositions send `0` to different points when composed in opposite orders.
  ⟨Equiv.swap 0 1, Equiv.swap 0 2, by decide⟩

end Solutions.GroupTheory.Permutations
