import Mathlib.GroupTheory.Perm.Sign
import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.GroupTheory.SpecificGroups.Alternating
import Mathlib.GroupTheory.SpecificGroups.Dihedral
import Mathlib.Tactic

namespace Solutions.GroupTheory.Permutations

open Equiv Equiv.Perm

theorem q1_swap_product :
    swap (0 : Fin 4) 1 * swap 1 2 * swap 2 3 = finRotate 4 := by
  -- Composing the three adjacent transpositions `(0 1)(1 2)(2 3)` threads every point one step
  -- forward: the result is the 4-cycle `0 → 1 → 2 → 3 → 0`.
  decide


theorem q2_sign_swap : Perm.sign (swap (0 : Fin 4) 1) = -1 := by
  -- A single transposition swaps two points and fixes the rest, so it is odd.
  decide


theorem q3_sign_cycle_length :
    Perm.sign (finRotate 4) = -1 ∧ Perm.sign (finRotate 5) = 1 := by
  -- A `k`-cycle is a product of `k - 1` transpositions, so its sign is `(-1)^{k-1}`: the 4-cycle
  -- is odd, the 5-cycle even.
  refine ⟨?_, ?_⟩ <;> decide


theorem q4_swaps_generate (σ : Perm (Fin 4)) :
    σ ∈ Subgroup.closure {τ : Perm (Fin 4) | τ.IsSwap} := by
  -- Build `σ` up one transposition at a time: the identity lies in every subgroup, and prepending
  -- a transposition keeps us inside the subgroup generated by the transpositions.
  refine swap_induction_on σ (Subgroup.one_mem _) ?_
  intro f x y hxy hf
  exact Subgroup.mul_mem _ (Subgroup.subset_closure ⟨x, y, hxy, rfl⟩) hf


theorem q5_three_cycle_even : Perm.sign (swap (0 : Fin 5) 1 * swap 1 2) = 1 := by
  -- A 3-cycle is a product of two transpositions, hence even.
  decide


theorem q6_alternating_index_two : (alternatingGroup (Fin 4)).index = 2 := by
  -- The alternating group is the kernel of `sign`, so its index is the size of the image of
  -- `sign`. Since `sign` is onto `{±1}`, that image has `2` elements.
  rw [show alternatingGroup (Fin 4) = (Equiv.Perm.sign).ker from rfl, Subgroup.index_ker,
    MonoidHom.range_eq_top.mpr (sign_surjective _),
    Nat.card_congr Subgroup.topEquiv.toEquiv, Nat.card_eq_fintype_card]
  rfl


theorem q7_order_eq_lcm :
    orderOf (swap (0 : Fin 5) 1 * (swap 2 3 * swap 3 4)) = 6 := by
  -- This element is a disjoint 2-cycle and 3-cycle. The order of a permutation is the least common
  -- multiple of its cycle lengths, here `lcm(2, 3) = 6`.
  rw [← lcm_cycleType]
  decide


theorem q8_cycle_decomp_concrete :
    (finRotate 4) ^ 2 = swap (0 : Fin 4) 2 * swap 1 3 := by
  -- Squaring the 4-cycle `0 → 1 → 2 → 3` sends `0 ↔ 2` and `1 ↔ 3`: it breaks into two disjoint
  -- transpositions.
  decide


theorem q9_fifteen_puzzle_parity : Perm.sign (swap (3 : Fin 15) 4) = -1 := by
  -- The 15-puzzle's tiles sit in `Fin 15`; swapping two of them while fixing the blank is a single
  -- transposition, which is odd. Legal moves are even permutations, so this swap is unreachable.
  decide


theorem q10_dihedral_in_S4 :
    ∃ f : DihedralGroup 4 →* Equiv.Perm (Fin 4), Function.Injective f := by
  -- Let the square's symmetries act on its four vertices `Fin 4`: a rotation is the 4-cycle
  -- `finRotate 4`, a reflection is the diagonal swap `(1 3)`. This action is faithful, giving an
  -- embedding of `D₄` into `S₄`.
  refine ⟨{ toFun := fun g => match g with
              | DihedralGroup.r i => (finRotate 4) ^ i.val
              | DihedralGroup.sr i => (Equiv.swap 1 3) * (finRotate 4) ^ i.val
            map_one' := by decide
            map_mul' := by decide }, ?_⟩
  decide

end Solutions.GroupTheory.Permutations
