import Mathlib.FieldTheory.SplittingField.Construction
import Mathlib.FieldTheory.SplittingField.IsSplittingField
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.Tactic

/-!
# Exercises — FieldTheory / Splitting Fields

A polynomial need not have all of its roots in its coefficient field.  A **splitting field** of a
polynomial `p : K[X]` is the smallest field extension of `K` in which `p` factors completely into
linear factors.  Equivalently, it is generated over `K` by the roots of `p`.  Splitting fields
always exist and are unique up to an isomorphism that fixes `K`; they are finite extensions of
`K`.  Algebraically closed fields, such as `ℂ`, are fields in which every polynomial already
splits.  Cyclotomic fields are splitting fields built from roots of unity.

Prove each statement yourself; canonical proofs live in
`Solutions/FieldTheory/03SplittingFields.lean`.
-/

namespace Exercises.FieldTheory.SplittingFields

open scoped Polynomial
open Polynomial

/-!
## Potentially helpful results

Basic tools you may want while solving the exercises below. **Hover** any name (or place the
cursor on the `#check` line and read the infoview) to see its exact statement.
-/
section

-- The construction and its roots
#check Polynomial.SplittingField.splits
#check Polynomial.SplittingField.adjoin_rootSet
#check Polynomial.Splits.exists_eval_eq_zero
#check Polynomial.mem_rootSet_of_ne
#check IsAlgebraic.isIntegral

-- Comparing two fields in which the same polynomial splits
#check Polynomial.IsSplittingField.algEquiv
#check Polynomial.IsSplittingField.splits_iff

-- Algebraic closedness and concrete complex roots
#check IsAlgClosed.splits
#check Complex.exists_root

-- Roots of unity and degree information
#check IsPrimitiveRoot.neg_one
#check Polynomial.Irreducible.natDegree_dvd_finrank

end

/-- **Question 1.**

Let `p : K[X]`.  Show that, after its coefficients are viewed in its splitting field, `p` splits
into linear factors. -/
theorem q1_splitting_field_splits {K : Type*} [Field K] (p : K[X]) :
    (p.map (algebraMap K (SplittingField p))).Splits := by
  sorry


/-- **Question 2.**

Show that the roots of `p` generate its splitting field over `K`. -/
theorem q2_generated_by_roots {K : Type*} [Field K] (p : K[X]) :
    Algebra.adjoin K (p.rootSet (SplittingField p)) = ⊤ := by
  sorry


/-- **Question 3.**

If `L` is any splitting field of `p` over `K`, prove that `L` is isomorphic to the chosen
splitting field by an isomorphism fixing every element of `K`. -/
theorem q3_uniqueness {K L : Type*} [Field K] [Field L] [Algebra K L] (p : K[X])
    [IsSplittingField K L p] : Nonempty (L ≃ₐ[K] SplittingField p) := by
  sorry


/-- **Question 4.**

Every nonconstant polynomial has a root in its splitting field. -/
theorem q4_root_in_splitting_field {K : Type*} [Field K] (p : K[X])
    (hp : p.natDegree ≠ 0) :
    ∃ x : SplittingField p, p.eval₂ (algebraMap K (SplittingField p)) x = 0 := by
  sorry


/-- **Question 5.**

Every root of `p` in its splitting field is integral over `K`.  Thus the splitting field is
generated by algebraic elements, rather than merely being presented through a finite-dimensional
typeclass. -/
theorem q5_roots_integral {K : Type*} [Field K] (p : K[X]) (x : SplittingField p)
    (hx : x ∈ p.rootSet (SplittingField p)) : IsIntegral K x := by
  sorry


/-- **Question 6.**

Show that `p` already splits over `K` exactly when its splitting field adds no new elements.  In
the formal statement, `⊤ = ⊥` says that the largest `K`-subalgebra of the splitting field is just
the copy of `K` itself. -/
theorem q6_splits_iff_no_extension {K : Type*} [Field K] (p : K[X]) :
    p.Splits ↔ (⊤ : Subalgebra K (SplittingField p)) = ⊥ := by
  sorry


/-- **Question 7.**

Prove that every complex polynomial splits into linear factors over `ℂ`. -/
theorem q7_complex_splits (p : ℂ[X]) : p.Splits := by
  sorry


/-- **Question 8.**

The fundamental theorem of algebra says that every nonconstant complex polynomial has a complex
root. -/
theorem q8_complex_root (p : ℂ[X]) (hp : 0 < p.degree) : ∃ z : ℂ, p.eval z = 0 := by
  sorry


/-- **Question 9.**

Verify directly that `i` is a root of `X² + 1` over `ℂ`. -/
theorem q9_x_sq_add_one_root : ((X ^ 2 + 1 : ℂ[X]).eval Complex.I) = 0 := by
  sorry


/-- **Question 10.**

Verify directly that `-1` is a primitive second root of unity in `ℚ`. -/
theorem q10_neg_one_primitive_root : IsPrimitiveRoot (-1 : ℚ) 2 := by
  sorry


/-- **Question 11.**

If `p` is irreducible, prove that its degree divides the degree of its splitting-field extension.
-/
theorem q11_irreducible_degree_dvd_splitting_degree {K : Type*} [Field K] (p : K[X])
    (hp : Irreducible p) : p.natDegree ∣ Module.finrank K (SplittingField p) := by
  sorry

end Exercises.FieldTheory.SplittingFields
