import Mathlib.FieldTheory.SplittingField.Construction
import Mathlib.FieldTheory.SplittingField.IsSplittingField
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.Tactic

/-!
# Exercises — FieldTheory / Splitting Fields

A polynomial need not have all of its roots in its coefficient field.  A **splitting field** of a
polynomial `p : K[X]` is the smallest field extension of `K` in which `p` factors completely into
linear factors.  Equivalently, it is generated over `K` by the roots of `p`.  Splitting fields
always exist and are unique up to an isomorphism that fixes `K`; they are finite extensions of
`K`.  Algebraically closed fields, such as `ℂ`, are fields in which every polynomial already
splits.  Cyclotomic fields are splitting fields built from roots of unity.

Prove each statement yourself; canonical proofs live in
`Solutions/FieldTheory/03SplittingFields.lean`.
-/

namespace Exercises.FieldTheory.SplittingFields

open scoped Polynomial
open Polynomial

/-!
## Potentially helpful results

Basic tools you may want while solving the exercises below. **Hover** any name (or place the
cursor on the `#check` line and read the infoview) to see its exact statement.
-/
section

-- The construction and its roots
#check Polynomial.SplittingField.splits
#check Polynomial.Splits.exists_eval_eq_zero
#check Polynomial.mem_rootSet_of_ne
#check IsAlgebraic.isIntegral

-- Factoring off a root and the cyclotomic polynomial for third roots of unity
#check Polynomial.dvd_iff_isRoot
#check Polynomial.cyclotomic

-- Roots of unity and degree information
#check IsPrimitiveRoot.neg_one

end

/-- The non-real third root of unity used in the concrete examples below. -/
noncomputable def omega : ℂ := (-1 + (Real.sqrt 3 : ℂ) * Complex.I) / 2

/-- **Question 1.**

Every nonconstant polynomial has a root in its splitting field. -/
theorem q1_root_in_splitting_field {K : Type*} [Field K] (p : K[X])
    (hp : p.natDegree ≠ 0) :
    ∃ x : SplittingField p, p.eval₂ (algebraMap K (SplittingField p)) x = 0 := by
  sorry


/-- **Question 2.**

Every root of `p` in its splitting field is integral over `K`.  Thus the splitting field is
generated by algebraic elements, rather than merely being presented through a finite-dimensional
typeclass. -/
theorem q2_roots_integral {K : Type*} [Field K] (p : K[X]) (x : SplittingField p)
    (hx : x ∈ p.rootSet (SplittingField p)) : IsIntegral K x := by
  sorry


/-- **Question 3.**

Over `ℚ`, factor `X³ - 1` as `(X - 1)(X² + X + 1)`. -/
theorem q3_factor_x_cubed_sub_one : (X ^ 3 - 1 : ℚ[X]) =
    (X - 1) * (X ^ 2 + X + 1) := by
  sorry


/-- **Question 4.**

The polynomial `X² + X + 1 ∈ ℚ[X]` has no rational root. -/
theorem q4_no_rational_root_x_sq_add_x_add_one (x : ℚ) : x ^ 2 + x + 1 ≠ 0 := by
  sorry


/-- **Question 5.**

For `ω = -1/2 + (√3/2)i`, verify that `ω² + ω + 1 = 0`. -/
theorem q5_omega_quadratic_relation : omega ^ 2 + omega + 1 = 0 := by
  sorry


/-- **Question 6.**

The number `ω` is a third root of unity. -/
theorem q6_omega_cubed_eq_one : omega ^ 3 = 1 := by
  sorry


/-- **Question 7.**

The number `ω` is a root of `X³ - 1` over `ℂ`. -/
theorem q7_omega_root_x_cubed_sub_one : ((X ^ 3 - 1 : ℂ[X]).eval omega) = 0 := by
  sorry


/-- **Question 8.**

The number `ω` is integral over `ℚ`. -/
theorem q8_omega_integral : IsIntegral ℚ omega := by
  sorry

end Exercises.FieldTheory.SplittingFields
