import Mathlib.RingTheory.Ideal.Int
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Ideal.Quotient.ChineseRemainder
import Mathlib.Data.ZMod.Basic
import Mathlib.RingTheory.Polynomial.Ideal
import Mathlib.Tactic

/-!
# Exercises — RingTheory / Ideals & Quotient Rings

Ideals are precisely the additive subgroups stable under multiplication by arbitrary ring
elements.  This condition makes quotient rings possible, and it translates structural properties
of a quotient into properties of the ideal: prime ideals give domains and maximal ideals give
fields.
-/

namespace Exercises.RingTheory.Ideals

variable {R S : Type*} [CommRing R] [CommRing S]

/-! ## Potentially helpful results -/
section

#check IsPrincipalIdealRing.principal
#check RingHom.quotientKerEquivRange
#check Ideal.Quotient.isDomain_iff_isPrime
#check Ideal.IsMaximal.isPrime
#check ZMod.chineseRemainder

end

/-- **Question 1.** Every ideal of the integers is generated by one integer. -/
theorem q1_ideals_of_int (I : Ideal ℤ) : ∃ n : ℤ, I = Ideal.span {n} := by sorry

/-- **Question 2.** The first isomorphism theorem identifies `R / ker f` with the range of `f`. -/
theorem q2_first_iso_ring (f : R →+* S) : Nonempty (R ⧸ f.ker ≃+* f.range) := by sorry

/-- **Question 3.** The quotient by an ideal is a domain exactly when that ideal is prime. -/
theorem q3_quotient_domain_iff_prime (I : Ideal R) : IsDomain (R ⧸ I) ↔ I.IsPrime := by sorry

/-- **Question 4.** Every maximal ideal in a commutative ring is prime. -/
theorem q4_maximal_prime (I : Ideal R) (hI : I.IsMaximal) : I.IsPrime := by sorry

/-- **Question 5.** Coprime moduli split as a product of quotient rings. -/
theorem q5_crt_ring (m n : ℕ) (h : m.Coprime n) :
    Nonempty (ZMod (m * n) ≃+* ZMod m × ZMod n) := by sorry

/-- **Question 6.** A prime integer generates a maximal ideal of `ℤ`. -/
theorem q6_int_prime_maximal (p : ℕ) [Fact p.Prime] : (Ideal.span ({p : ℤ})).IsMaximal := by sorry

/-- **Question 7.** The ideal generated by a prime integer is prime. -/
theorem q7_int_prime_ideal (p : ℕ) [Fact p.Prime] : (Ideal.span ({p : ℤ})).IsPrime := by sorry

/-- **Question 8.** The zero ideal of the integers is prime: `ℤ` is a domain. -/
theorem q8_zero_ideal_prime : (⊥ : Ideal ℤ).IsPrime := by sorry

/-- **Question 9.** Evaluation at zero exhibits `(X)` as the kernel of the constant-coefficient
map on `R[X]`. -/
theorem q9_kernel_constant_coeff :
    RingHom.ker (Polynomial.constantCoeff : R[X] →+* R) = Ideal.span {Polynomial.X} := by sorry

/-- **Question 10.** Ring homomorphisms preserve nilpotence. -/
theorem q10_map_nilpotent (f : R →+* S) (x : R) (n : ℕ) (hx : x ^ n = 0) :
    (f x) ^ n = 0 := by sorry

/-- **Question 11.** The two-generator ideal `(2, X)` in `ℤ[X]` contains both of its named
generators, illustrating why polynomial-ring ideals need not look like integer ideals. -/
theorem q11_two_X_mem_span :
    (2 : ℤ[X]) ∈ Ideal.span ({(2 : ℤ[X]), Polynomial.X} : Set ℤ[X]) ∧
      Polynomial.X ∈ Ideal.span ({(2 : ℤ[X]), Polynomial.X} : Set ℤ[X]) := by sorry

end Exercises.RingTheory.Ideals
