import Mathlib.RingTheory.Ideal.Int
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Ideal.Quotient.ChineseRemainder
import Mathlib.Data.ZMod.Basic
import Mathlib.RingTheory.Polynomial.Ideal
import Mathlib.Tactic

/-!
# Exercises — RingTheory / Ideals & Quotient Rings

Ideals are precisely the additive subgroups stable under multiplication by arbitrary ring
elements.  This condition makes quotient rings possible, and it translates structural properties
of a quotient into properties of the ideal: prime ideals give domains and maximal ideals give
fields.

Prove each statement yourself; the canonical proofs live in
`Solutions/RingTheory/02Ideals.lean`. Do **not** commit your proofs into this file.
-/

namespace Exercises.RingTheory.Ideals

open scoped Polynomial

variable {R S : Type*} [CommRing R] [CommRing S]

/-! ## Potentially helpful results -/
section

-- Principal ideals and generated ideals.
#check IsPrincipalIdealRing.principal
#check Ideal.mem_span_singleton
#check Ideal.subset_span

-- Quotients and maps out of them.
#check Ideal.Quotient.lift
#check RingHom.lift_injective_of_ker_le_ideal
#check Ideal.Quotient.lift_surjective_of_surjective
#check Ideal.Quotient.eq_zero_iff_mem
#check RingEquiv.ofBijective

-- Prime and maximal ideals through their quotients.
#check Ideal.Quotient.exists_inv
#check eq_zero_or_eq_zero_of_mul_eq_zero

-- Concrete arithmetic in `ℤ` and polynomial rings.
#check ZMod.chineseRemainder
#check Int.gcd_dvd_left
#check Int.gcd_dvd_right
#check Int.gcd_eq_gcd_ab
#check Polynomial.X_dvd_iff

end

/-- **Question 1.**

Every ideal of the integers is generated by one integer.

This is an application exercise: use the fact that `ℤ` is a principal ideal ring. -/
theorem q1_ideals_of_int (I : Ideal ℤ) : ∃ n : ℤ, I = Ideal.span {n} := by sorry


/-- **Question 2.**

The first isomorphism theorem identifies `R / ker f` with the range of `f`.

Prove without using `RingHom.quotientKerEquivRange` (or either
`RingHom.quotientKerEquivOfSurjective` or `RingHom.quotientKerEquivOfRightInverse`). -/
theorem q2_first_iso_ring (f : R →+* S) : Nonempty (R ⧸ RingHom.ker f ≃+* f.range) := by sorry


/-- **Question 3.**

The quotient by an ideal is a domain exactly when that ideal is prime.

Prove without using `Ideal.Quotient.isDomain_iff_prime`. -/
theorem q3_quotient_domain_iff_prime (I : Ideal R) : IsDomain (R ⧸ I) ↔ I.IsPrime := by sorry


/-- **Question 4.**

The quotient by an ideal is a field exactly when that ideal is maximal.

Prove without using `Ideal.Quotient.maximal_ideal_iff_isField_quotient`. -/
theorem q4_quotient_field_iff_maximal (I : Ideal R) : I.IsMaximal ↔ IsField (R ⧸ I) := by sorry


/-- **Question 5.**

Every maximal ideal in a commutative ring is prime.

Prove without using `Ideal.IsMaximal.isPrime`. -/
theorem q5_maximal_prime (I : Ideal R) (hI : I.IsMaximal) : I.IsPrime := by sorry


/-- **Question 6.**

Coprime moduli split as a product of quotient rings.

This is an application exercise: use the Chinese remainder theorem. -/
theorem q6_crt_ring (m n : ℕ) (h : m.Coprime n) :
    Nonempty (ZMod (m * n) ≃+* ZMod m × ZMod n) := by sorry


/-- **Question 7.**

A prime integer generates a maximal ideal of `ℤ`: the ideal `(p)` is proper and every strictly
larger ideal is the whole ring. -/
theorem q7_int_prime_maximal (p : ℕ) [Fact p.Prime] :
    Ideal.span ({(p : ℤ)} : Set ℤ) ≠ ⊤ ∧
    ∀ J : Ideal ℤ, Ideal.span ({(p : ℤ)} : Set ℤ) < J → J = ⊤ := by sorry


/-- **Question 8.**

The zero ideal of `ℤ` is prime but not maximal. Thus a prime ideal need not be maximal.

Prove without using `Ideal.isPrime_bot`. -/
theorem q8_zero_prime_not_maximal : (⊥ : Ideal ℤ).IsPrime ∧ ¬ (⊥ : Ideal ℤ).IsMaximal := by sorry


/-- **Question 9.**

Evaluation at zero exhibits `(X)` as the kernel of the constant-coefficient map on `R[X]`.

Prove without using `Polynomial.ker_constantCoeff`. -/
theorem q9_kernel_constant_coeff :
    RingHom.ker (Polynomial.constantCoeff : R[X] →+* R) = Ideal.span {Polynomial.X} := by sorry


/-- **Question 10.**

Ring homomorphisms preserve nilpotence. -/
theorem q10_map_nilpotent (f : R →+* S) (x : R) (n : ℕ) (hx : x ^ n = 0) :
    (f x) ^ n = 0 := by sorry


/-- **Question 11.**

The two-generator ideal `(2, X)` in `ℤ[X]` contains both of its named generators. -/
theorem q11_two_X_mem_span :
    (2 : ℤ[X]) ∈ Ideal.span ({(2 : ℤ[X]), Polynomial.X} : Set ℤ[X]) ∧
      Polynomial.X ∈ Ideal.span ({(2 : ℤ[X]), Polynomial.X} : Set ℤ[X]) := by sorry

end Exercises.RingTheory.Ideals
