import Mathlib.RingTheory.Ideal.Int
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Polynomial.Ideal
import Mathlib.Tactic

/-!
# Exercises — RingTheory / Ideals & Quotient Rings

Ideals are precisely the additive subgroups stable under multiplication by arbitrary ring
elements.  This condition makes quotient rings possible, and it translates structural properties
of a quotient into properties of the ideal: prime ideals give domains and maximal ideals give
fields.

Prove each statement yourself; the canonical proofs live in
`Solutions/RingTheory/02Ideals.lean`. Do **not** commit your proofs into this file.
-/

namespace Exercises.RingTheory.Ideals

open scoped Polynomial

variable {R S : Type*} [CommRing R] [CommRing S]

/-! ## Potentially helpful results -/
section

-- Principal ideals and generated ideals.
#check @Ideal.mem_span_singleton
#check @Ideal.subset_span

-- Quotients and maps out of them.
#check @Ideal.Quotient.lift
#check @RingHom.lift_injective_of_ker_le_ideal
#check @Ideal.Quotient.lift_surjective_of_surjective
#check @Ideal.Quotient.eq_zero_iff_mem
#check @RingEquiv.ofBijective

-- Prime and maximal ideals through their quotients.
#check @Ideal.mem_span_singleton_sup
#check @eq_zero_or_eq_zero_of_mul_eq_zero

-- Concrete arithmetic in `ℤ` and polynomial rings.
#check @Int.gcd_dvd_left
#check @Int.gcd_dvd_right
#check @Int.gcd_eq_gcd_ab
#check @Polynomial.X_dvd_iff

end


/-- **Question 1.**

The ideal generated by `6` and `15` is `(3)`.

Show each inclusion: `3` divides both generators, while `3 = -2 · 6 + 15`. -/
theorem q1_span_six_fifteen :
    Ideal.span ({(6 : ℤ), 15} : Set ℤ) = Ideal.span ({3} : Set ℤ) := by
  sorry


/-- **Question 2.**

The first isomorphism theorem identifies `R / ker f` with the range of `f`.

Prove without using `RingHom.quotientKerEquivRange` (or either
`RingHom.quotientKerEquivOfSurjective` or `RingHom.quotientKerEquivOfRightInverse`). -/
theorem q2_first_iso_ring (f : R →+* S) : Nonempty (R ⧸ RingHom.ker f ≃+* f.range) := by
  sorry


/-- **Question 3.**

The quotient by an ideal is a domain exactly when that ideal is prime.

Prove without using `Ideal.Quotient.isDomain_iff_prime` or `Ideal.Quotient.isDomain`. -/
theorem q3_quotient_domain_iff_prime (I : Ideal R) : IsDomain (R ⧸ I) ↔ I.IsPrime := by
  sorry


/-- **Question 4.**

The quotient by an ideal is a field exactly when that ideal is maximal. For the forward direction,
adjoin a representative `x ∉ I` to `I`; maximality forces `1 = yx + z` with `z ∈ I`, and this
identity supplies the inverse of the class of `x`.

Prove without using `Ideal.Quotient.maximal_ideal_iff_isField_quotient`,
`Ideal.Quotient.field`, `Ideal.Quotient.maximal_of_isField`, or `Ideal.Quotient.exists_inv`. -/
theorem q4_quotient_field_iff_maximal (I : Ideal R) : I.IsMaximal ↔ IsField (R ⧸ I) := by
  sorry


/-- **Question 5.**

Every maximal ideal in a commutative ring is prime.

Prove without using `Ideal.IsMaximal.isPrime`. -/
theorem q5_maximal_prime (I : Ideal R) (hI : I.IsMaximal) : I.IsPrime := by
  sorry


/-- **Question 6.**

A prime integer generates a maximal ideal of `ℤ`: the ideal `(p)` is proper and every strictly
larger ideal is the whole ring. -/
theorem q6_int_prime_maximal (p : ℕ) [Fact p.Prime] :
    Ideal.span ({(p : ℤ)} : Set ℤ) ≠ ⊤ ∧
    ∀ J : Ideal ℤ, Ideal.span ({(p : ℤ)} : Set ℤ) < J → J = ⊤ := by
  sorry


/-- **Question 7.**

The zero ideal of `ℤ` is prime but not maximal. Thus a prime ideal need not be maximal.

Prove without using `Ideal.isPrime_bot`. -/
theorem q7_zero_prime_not_maximal : (⊥ : Ideal ℤ).IsPrime ∧ ¬ (⊥ : Ideal ℤ).IsMaximal := by
  sorry


/-- **Question 8.**

Evaluation at zero exhibits `(X)` as the kernel of the constant-coefficient map on `R[X]`.

Prove without using `Polynomial.ker_constantCoeff`. -/
theorem q8_kernel_constant_coeff :
    RingHom.ker (Polynomial.constantCoeff : R[X] →+* R) = Ideal.span {Polynomial.X} := by
  sorry

end Exercises.RingTheory.Ideals
