import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Data.ZMod.Basic
import Mathlib.Data.Nat.Totient
import Mathlib.RingTheory.RootsOfUnity.Complex
import Mathlib.Tactic

/-!
# Exercises — GroupTheory / Cyclic

A group is **cyclic** when it is generated by a single element: `G = ⟨g⟩ = {gᵏ}`. Up to isomorphism
there are only two kinds — the infinite cyclic group `ℤ`, and the finite `ℤ/n` — so "cyclic"
completely classifies. The order of the generator equals `|G|`, and `gᵏ` has order `n / gcd(n, k)`,
so the generators of `ℤ/n` are exactly the residues coprime to `n` (there are `φ(n)` of them). The
subgroup structure is astonishingly rigid: **every subgroup of a cyclic group is cyclic**, and a
finite cyclic group has **exactly one** subgroup of each order dividing `n` — the divisor lattice
*is* the subgroup lattice.

Prove each statement yourself; the canonical proofs live in `Solutions/GroupTheory/02Cyclic.lean`. Do
**not** commit your proofs into this file.

Some exercises ask you to prove *without using* a particular lemma (e.g. "Prove without using
`orderOf_pow`") — the point is to rebuild that result from more primitive facts. These bans are
enforced automatically when you build the project.
-/

namespace Exercises.GroupTheory.Cyclic

open Subgroup

variable {G : Type*} [Group G]

/-!
## Potentially helpful results

Basic tools you may want while solving the exercises below. **Hover** any name to see its exact
statement.
-/
section

-- Order and powers: divisibility characterisation of the order, and `g^{orderOf g} = 1`.
#check @orderOf_dvd_of_pow_eq_one
#check @pow_orderOf_eq_one
#check @orderOf_pos

-- Number theory of exponents: the coprime cofactors and the Bézout identity for `gcd`.
#check @Nat.coprime_div_gcd_div_gcd
#check @Nat.gcd_eq_gcd_ab
#check @Nat.div_div_self

-- Cyclic groups: a generator, and order-vs-cardinality.
#check @IsCyclic.exists_generator
#check @orderOf_eq_card_of_forall_mem_zpowers
#check @isCyclic_of_orderOf_eq_card

-- The subgroup generated by one element.
#check @Nat.card_zpowers
#check @Subgroup.zpowers_le
#check @Subgroup.mem_zpowers_iff

-- Additive orders and multiples (for `ZMod` / `ℤ`).
#check @addOrderOf_dvd_of_nsmul_eq_zero
#check @AddSubgroup.mem_zmultiples_iff

end

/-- **Question 1.**

Before finding the order of `g^k`, translate the question into arithmetic: a power of `g^k` is the
identity exactly when the order of `g` divides the corresponding product of exponents. -/
theorem q1_powerOf_pow_eq_one_iff [Finite G] (g : G) (k m : ℕ) :
    (g ^ k) ^ m = 1 ↔ orderOf g ∣ k * m := by
  sorry


/-- **Question 2.**

If `orderOf g = n`, then `orderOf (gᵏ) = n / gcd(n, k)`. Work in three stages: use the warm-up to
show that `n / gcd(n,k)` is an exponent of `g^k`; use Bézout/coprimality to show every exponent is
a multiple of it; conclude by divisibility antisymmetry.

Prove without using `orderOf_pow`. -/
theorem q2_orderOf_pow [Finite G] (g : G) (k : ℕ) :
    orderOf (g ^ k) = orderOf g / (orderOf g).gcd k := by
  sorry


/-- **Question 3.**

`gᵏ` has the same order as `g` — equivalently, in a cyclic group generated by `g` it again generates
the whole group — exactly when `gcd(orderOf g, k) = 1`. -/
theorem q3_generator_iff_coprime [Finite G] (g : G) (k : ℕ) :
    orderOf (g ^ k) = orderOf g ↔ Nat.Coprime (orderOf g) k := by
  sorry


/-- **Question 4.**

The generators of the additive group `ZMod 12` are exactly the residues coprime to `12`, namely
`1, 5, 7, 11`. -/
theorem q4_generators_zmod :
    Finset.univ.filter (fun a : ZMod 12 => Nat.Coprime a.val 12) = {1, 5, 7, 11} := by
  sorry


/-- **Question 5.**

Every subgroup of a cyclic group is cyclic.

Prove without using `Subgroup.isCyclic`. -/
theorem q5_subgroup_isCyclic [IsCyclic G] (H : Subgroup G) : IsCyclic H := by
  sorry


/-- **Question 6.**

A finite cyclic group has exactly one subgroup of each order `d` dividing `|G|`.

Prove without using `Subgroup.isCyclic`. -/
theorem q6_unique_subgroup_per_divisor [Finite G] [IsCyclic G] {d : ℕ}
    (hd : d ∣ Nat.card G) : ∃! H : Subgroup G, Nat.card H = d := by
  sorry


/-- **Question 7.**

A finite group is cyclic iff it has an element whose order equals the group's cardinality. -/
theorem q7_cyclic_iff_full_order [Fintype G] :
    IsCyclic G ↔ ∃ g : G, orderOf g = Fintype.card G := by
  sorry


/-- **Question 8.**

`ZMod 12` has exactly `φ(12) = 4` generators (the residues coprime to `12`, counted in q3). -/
theorem q8_card_generators_zmod :
    (Finset.univ.filter (fun a : ZMod 12 => Nat.Coprime a.val 12)).card = Nat.totient 12 := by
  sorry


/-- **Question 9.**

The only generators of the additive group `ℤ` are `1` and `-1`. -/
theorem q9_int_generators (a : ℤ) :
    AddSubgroup.zmultiples a = ⊤ ↔ a = 1 ∨ a = -1 := by
  sorry


/-- **Question 10.**

The Klein four-group `ZMod 2 × ZMod 2` is **not** cyclic: every element has order dividing `2`, so
no element has the order `4` a generator would need. -/
theorem q10_klein_not_cyclic : ¬ IsAddCyclic (ZMod 2 × ZMod 2) := by
  sorry


/-- **Question 11.**

The group `μₙ` of complex `n`-th **roots of unity** — the subgroup `rootsOfUnity n ℂ` of `ℂˣ`,
i.e. the solutions of `zⁿ = 1` — is **cyclic of order `n`** (equivalently `μₙ ≅ ℤ/n`). -/
theorem q11_roots_of_unity (n : ℕ) [NeZero n] :
    IsCyclic (rootsOfUnity n ℂ) ∧ Nat.card (rootsOfUnity n ℂ) = n := by
  sorry

end Exercises.GroupTheory.Cyclic
