import Mathlib.GroupTheory.Perm.Sign
import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.GroupTheory.SpecificGroups.Alternating
import Mathlib.GroupTheory.SpecificGroups.Dihedral
import Mathlib.Tactic

/-!
# Exercises — GroupTheory / Permutations

The **symmetric group** `Sₙ` is the group of all bijections of an `n`-element set — the concrete,
non-abelian playground where abstract group theory becomes hands-on. Every permutation factors
**uniquely into disjoint cycles**, and every permutation is a product of **transpositions**; the
*parity* of the number of transpositions is well defined, giving the **sign** homomorphism
`sign : Sₙ → {±1}`. Its kernel is the **alternating group** `Aₙ` of even permutations, a subgroup of
index `2`. The order of a permutation is the least common multiple of its cycle lengths.

Here `Sₙ = Equiv.Perm (Fin n)`, `Equiv.swap i j` is the transposition of `i` and `j`, and
`finRotate n` is the `n`-cycle `0 → 1 → ⋯ → n-1 → 0`.

Prove each statement yourself; the canonical proofs live in
`Solutions/GroupTheory/03Permutations.lean`. Do **not** commit your proofs into this file.

Some exercises ask you to prove *without using* a particular lemma — the point is to rebuild that
result from more primitive facts. These bans are enforced when you build the project.
-/

namespace Exercises.GroupTheory.Permutations

open Equiv Equiv.Perm

/-!
## Potentially helpful results

Basic tools you may want while solving the exercises below. **Hover** any name to see its exact
statement.
-/
section

-- Building a permutation up from transpositions, and the generators of a subgroup.
#check @Equiv.Perm.swap_induction_on
#check @Subgroup.subset_closure
#check @Subgroup.mul_mem

-- The sign homomorphism: surjectivity onto `{±1}`, and the index of a kernel.
#check @Equiv.Perm.sign_surjective
#check @MonoidHom.range_eq_top
#check @Subgroup.index_ker

-- The order of a permutation from its cycle type.
#check @Equiv.Perm.lcm_cycleType

end

/-- **Question 1.**

Write the product of adjacent transpositions `(0 1)(1 2)(2 3)` in cycle form: it equals the 4-cycle
`finRotate 4` (the cycle `0 → 1 → 2 → 3 → 0`). -/
theorem q1_swap_product :
    swap (0 : Fin 4) 1 * swap 1 2 * swap 2 3 = finRotate 4 := by
  sorry


/-- **Question 2.**

A transposition is odd: `sign (swap 0 1) = -1` in `S₄`. -/
theorem q2_sign_swap : Perm.sign (swap (0 : Fin 4) 1) = -1 := by
  sorry


/-- **Question 3.**

The sign of a `k`-cycle is `(-1)^{k-1}`: the 4-cycle `finRotate 4` is odd, the 5-cycle `finRotate 5`
is even. -/
theorem q3_sign_cycle_length :
    Perm.sign (finRotate 4) = -1 ∧ Perm.sign (finRotate 5) = 1 := by
  sorry


/-- **Question 4.**

Every permutation is a product of transpositions: it lies in the subgroup generated by all
transpositions (`τ.IsSwap` means `τ` is a transposition).

Prove without using `Equiv.Perm.closure_isSwap`. -/
theorem q4_swaps_generate (σ : Perm (Fin 4)) :
    σ ∈ Subgroup.closure {τ : Perm (Fin 4) | τ.IsSwap} := by
  sorry


/-- **Question 5.**

A 3-cycle is even: `sign = 1`. -/
theorem q5_three_cycle_even : Perm.sign (swap (0 : Fin 5) 1 * swap 1 2) = 1 := by
  sorry


/-- **Question 6.**

The alternating group `A₄` (the even permutations, `= ker sign`) has index `2` in `S₄`.

Prove without using `alternatingGroup.index_eq_two`. -/
theorem q6_alternating_index_two : (alternatingGroup (Fin 4)).index = 2 := by
  sorry


/-- **Question 7.**

The order of a permutation is the least common multiple of its cycle lengths. For the disjoint
`2`-cycle and `3`-cycle below, that is `lcm(2, 3) = 6`. -/
theorem q7_order_eq_lcm :
    orderOf (swap (0 : Fin 5) 1 * (swap 2 3 * swap 3 4)) = 6 := by
  sorry


/-- **Question 8.**

Disjoint-cycle decomposition: the square of the 4-cycle `finRotate 4` splits into two disjoint
transpositions `(0 2)` and `(1 3)`. -/
theorem q8_cycle_decomp_concrete :
    (finRotate 4) ^ 2 = swap (0 : Fin 4) 2 * swap 1 3 := by
  sorry


/-- **Question 9.**

One parity ingredient of the **15-puzzle**: swapping two tiles while fixing the blank is odd. The
full puzzle obstruction additionally requires proving that legal moves preserve the relevant parity;
that separate invariant is not formalized here. -/
theorem q9_fifteen_puzzle_parity : Perm.sign (swap (3 : Fin 15) 4) = -1 := by
  sorry


/-- **Question 10.**

The rotation `r = (0 1 2 3)` and reflection `s = (1 3)` of a square obey the dihedral relations
`r⁴ = 1`, `s² = 1`, and `srs = r⁻¹`. -/
theorem q10_square_dihedral_relations :
    (finRotate 4) ^ 4 = 1 ∧ (swap (1 : Fin 4) 3) ^ 2 = 1 ∧
      swap 1 3 * finRotate 4 * swap 1 3 = (finRotate 4)⁻¹ := by
  sorry


/-- **Question 11.**

The symmetric group on three points is non-abelian. Exhibit two overlapping transpositions that do
not commute. This is the first concrete reminder that a permutation group need not be abelian. -/
theorem q11_noncommutative : ∃ σ τ : Equiv.Perm (Fin 3), σ * τ ≠ τ * σ := by
  sorry

end Exercises.GroupTheory.Permutations
