import Mathlib.Algebra.Group.Hom.Basic
import Mathlib.Algebra.Group.Subgroup.Ker
import Mathlib.GroupTheory.Perm.Basic
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.GroupTheory.SpecificGroups.Quaternion
import Mathlib.GroupTheory.SpecificGroups.Dihedral
import Mathlib.Algebra.Group.Opposite
import Mathlib.Data.ZMod.Basic
import Mathlib.CategoryTheory.Groupoid
import Mathlib.Tactic

/-!
# Exercises — GroupTheory / Homomorphisms & Isomorphisms

A group homomorphism preserves multiplication. Its kernel measures precisely what it collapses, and
its image records what it reaches. Kernels are normal, isomorphisms preserve element orders, and
Cayley's theorem realizes every group as a group of permutations. The final two questions give a
first look at categories: groups with homomorphisms form a category, while a single group is a
one-object groupoid.

Prove each statement yourself; canonical proofs live in `Solutions/GroupTheory/05Homomorphisms.lean`.
Do not commit proofs into this file. Bans are enforced when you build the project.
-/

namespace Exercises.GroupTheory.Homomorphisms

open CategoryTheory

variable {G H : Type*} [Group G] [Group H]

/-!
## Potentially helpful results

Basic tools for kernels, cyclic generators, and element orders. **Hover** any name (or place the
cursor on the `#check` line and read the infoview) to see its exact statement.
-/
section

-- Reading membership in a kernel and in the cyclic subgroup generated by one element.
#check @MonoidHom.mem_ker
#check @Subgroup.mem_zpowers_iff

-- Powers that return to the identity, and their additive analogue.
#check @pow_orderOf_eq_one
#check @AddSubgroup.mem_zmultiples_iff

end


/-- **Question 1.**

A homomorphism sends inverses to inverses. Show that `f a⁻¹` is an inverse of `f a`, then use
uniqueness of inverses. -/
theorem q1_map_inv (f : G →* H) (a : G) : f a⁻¹ = (f a)⁻¹ := by
  sorry


/-- **Question 2.**

A homomorphism is injective exactly when its kernel is trivial.

Prove without using `MonoidHom.ker_eq_bot_iff`. -/
theorem q2_injective_iff_ker (f : G →* H) : Function.Injective f ↔ f.ker = ⊥ := by
  sorry


/-- **Question 3.**

The kernel of every group homomorphism is a normal subgroup.

Prove without using `MonoidHom.normal_ker`. -/
theorem q3_ker_normal (f : G →* H) : f.ker.Normal := by
  sorry


/-- **Question 4.**

Cayley's theorem: every group embeds into the permutation group of its underlying set.

Prove without using `MulAction.toPermHom`. -/
theorem q4_cayley : ∃ φ : G →* Equiv.Perm G, Function.Injective φ := by
  sorry


/-- **Question 5.**

A homomorphism out of a cyclic group is determined by the image of a generator. -/
theorem q5_hom_cyclic_determined (g : G) (hg : Subgroup.zpowers g = ⊤) (f h : G →* H)
    (hgen : f g = h g) : f = h := by
  sorry


/-- **Question 6.**

An isomorphism preserves the order of every element. Compare the powers that return to the
identity in each group. -/
theorem q6_iso_preserves_orderOf (e : G ≃* H) (a : G) : orderOf (e a) = orderOf a := by
  sorry


/-- **Question 7.**

For reduction modulo `6`, `12` lies in the kernel while `5` does not. Verify both claims by
computing the two residue classes. -/
theorem q7_mod_six_kernel_examples :
    (12 : ℤ) ∈ (Int.castAddHom (ZMod 6)).ker ∧ (5 : ℤ) ∉ (Int.castAddHom (ZMod 6)).ker := by
  sorry


/-- **Question 8.**

The additive group `ZMod 6` is generated by the residue class of `1`. Show that every residue is
an integer multiple of `1`. -/
theorem q8_zmod_six_generated_by_one : AddSubgroup.zmultiples (1 : ZMod 6) = ⊤ := by
  sorry

/-- A group together with its carrier, used in the categorical exercise. -/
structure GrpObj where
  carrier : Type
  group : Group carrier

attribute [instance] GrpObj.group

/-- The data and laws of the one-object groupoid attached to a group. -/
structure OneObjectGroupoid (K : Type) [Group K] where
  identity : K
  composition : K → K → K
  inverse : K → K
  identity_eq : identity = 1
  composition_eq : ∀ f g, composition f g = g * f
  inverse_eq : ∀ f, inverse f = f⁻¹
  id_comp : ∀ f, composition identity f = f
  comp_id : ∀ f, composition f identity = f
  assoc : ∀ f g h, composition (composition f g) h = composition f (composition g h)
  inv_comp : ∀ f, composition (inverse f) f = identity
  comp_inv : ∀ f, composition f (inverse f) = identity


/-- **Question 9.**

A group can be viewed as a category with one object: its elements are the arrows, multiplication is
composition (in the category-theory order), and inverses make every arrow invertible. Construct
that groupoid from `K`. -/
theorem q9_group_as_groupoid (K : Type) [Group K] : Nonempty (OneObjectGroupoid K) := by
  sorry


/-- **Question 10.**

The quaternion group `Q₈` and the dihedral group `D₄` both have order `8`, but are not isomorphic.
Use an isomorphism to transport the solutions of `x² = 1`, then compare their counts. -/
theorem q10_q8_not_iso_d4 : IsEmpty (QuaternionGroup 2 ≃* DihedralGroup 4) := by
  sorry


/-- **Question 11.**

The opposite group reverses multiplication. Construct the isomorphism from `G` to `Gᵐᵒᵖ` that sends
each element to its inverse. -/
theorem q11_opposite_iso :
    ∃ e : G ≃* Gᵐᵒᵖ, ∀ x, e x = MulOpposite.op x⁻¹ := by
  sorry

end Exercises.GroupTheory.Homomorphisms
