import Mathlib.FieldTheory.SplittingField.Construction
import Mathlib.FieldTheory.SplittingField.IsSplittingField
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.Tactic

namespace Solutions.FieldTheory.SplittingFields

open scoped Polynomial
open Polynomial

theorem q1_splitting_field_splits {K : Type*} [Field K] (p : K[X]) :
    (p.map (algebraMap K (SplittingField p))).Splits := by
  -- The defining feature of the construction is that every factor becomes linear.
  exact SplittingField.splits p

theorem q2_generated_by_roots {K : Type*} [Field K] (p : K[X]) :
    Algebra.adjoin K (p.rootSet (SplittingField p)) = ⊤ := by
  -- No smaller subfield suffices: the roots generate the whole extension.
  exact SplittingField.adjoin_rootSet p

theorem q3_uniqueness {K L : Type*} [Field K] [Field L] [Algebra K L] (p : K[X])
    [IsSplittingField K L p] : Nonempty (L ≃ₐ[K] SplittingField p) := by
  -- Two fields generated by all the roots of the same polynomial are the same over `K`.
  exact ⟨IsSplittingField.algEquiv L p⟩

theorem q4_root_in_splitting_field {K : Type*} [Field K] (p : K[X])
    (hp : p.natDegree ≠ 0) :
    ∃ x : SplittingField p, p.eval₂ (algebraMap K (SplittingField p)) x = 0 := by
  -- A nonconstant product of linear factors has at least one linear factor, hence a root.
  obtain ⟨x, hx⟩ := (q1_splitting_field_splits p).exists_eval_eq_zero (by
    simpa only [Polynomial.degree_map, Nat.cast_zero] using
      (Polynomial.degree_ne_of_natDegree_ne hp))
  exact ⟨x, by simpa only [Polynomial.eval₂_eq_eval_map] using hx⟩

theorem q5_roots_integral {K : Type*} [Field K] (p : K[X]) (x : SplittingField p)
    (hx : x ∈ p.rootSet (SplittingField p)) : IsIntegral K x := by
  have hp : p ≠ 0 := by
    intro hp
    simp [hp] at hx
  -- A root satisfies a nonzero polynomial over `K`, so it is algebraic and hence integral.
  apply IsAlgebraic.isIntegral
  refine ⟨p, hp, ?_⟩
  exact (Polynomial.mem_rootSet_of_ne hp).mp hx

theorem q6_splits_iff_no_extension {K : Type*} [Field K] (p : K[X]) :
    p.Splits ↔ (⊤ : Subalgebra K (SplittingField p)) = ⊥ := by
  -- If all roots were already in `K`, adjoining them does not enlarge `K`, and conversely.
  exact IsSplittingField.splits_iff (SplittingField p) p

theorem q7_complex_splits (p : ℂ[X]) : p.Splits := by
  -- Algebraic closedness is precisely the assertion that every polynomial splits.
  exact IsAlgClosed.splits p

theorem q8_complex_root (p : ℂ[X]) (hp : 0 < p.degree) : ∃ z : ℂ, p.eval z = 0 := by
  -- A positive degree polynomial cannot avoid all complex numbers.
  simpa only [Polynomial.IsRoot] using Complex.exists_root hp

theorem q9_x_sq_add_one_root : ((X ^ 2 + 1 : ℂ[X]).eval Complex.I) = 0 := by
  norm_num

theorem q10_neg_one_primitive_root : IsPrimitiveRoot (-1 : ℚ) 2 := by
  -- In characteristic zero, `-1` has square one and is not itself one.
  exact IsPrimitiveRoot.neg_one 0 (by norm_num)

theorem q11_irreducible_degree_dvd_splitting_degree {K : Type*} [Field K] (p : K[X])
    (hp : Irreducible p) : p.natDegree ∣ Module.finrank K (SplittingField p) := by
  -- The irreducible polynomial contributes the degree of any one of its roots; that simple
  -- subextension is contained in the field containing all roots.
  exact hp.natDegree_dvd_finrank (q1_splitting_field_splits p)

end Solutions.FieldTheory.SplittingFields
