name: CI

on:
  push:
  pull_request:

jobs:
  build-and-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test style lint
        run: bash Meta/scripts/test-style-lint.sh
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: .
      - name: Check repository style
        run: bash Meta/scripts/style-lint.sh
